name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_agnes16 }}/2048-agnes:latest

jobs:
  build-push-image:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check IMAGE_NAME
        run: echo "IMAGE_NAME=$IMAGE_NAME"

      - name: Build Image
        run: docker build -t $IMAGE_NAME .

      - name: List Image
        run: docker images

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_agnes16 }}
          password: ${{ secrets.DOCKER_taufiqtabarak }}

      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy-2048:
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: stop and remove existing container
        run: docker compose down --rmi all

      - name: start container
        run: docker compose up -d
